[package]
name = "shars"
version = "1.2.0"
authors = ["bxni"]
edition = "2024"
description = "A SHA-256 checksum utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
colored = "3.0.0"
walkdir = "2.5.0"
regex-lite = "0.1.6"
encoding_rs = "0.8.35"
clap = { version = "4.4", features = ["derive", "cargo"] }
rayon = "1.8"
tokio = { version = "1.43", features = ["full"] }
indicatif = "0.17"

[dev-dependencies] 
tempfile = "3.8"