[package]
name = "shars"
version = "1.2.0"
authors = ["bxni"]
edition = "2024"
description = "A SHA-256 checksum utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
anyhow = "1"
clap = { version = "4.4", features = ["derive", "cargo"] }
rayon = "1.8"
walkdir = "2.4"
indicatif = "0.17"
colored = "3.0.0"

[profile.release]
codegen-units = 1
strip = true

[dev-dependencies] 
tempfile = "3.8"
